CREATE OR REPLACE FUNCTION getTempSeason()
RETURNS SETOF anyelement AS $fuc$

BEGIN
	CREATE VIEW TEMP AS SELECT SUM	(Usage) FROM METER_ENTRY WHERE EXTRACT(MONTH FROM Start_date) >=3 AND EXTRACT(MONTH FROM End_date) <= 6;
	CREATE VIEW Result AS SELECT eff_factor FROM Building WHERE name = 'Cromwell Hall';
	CREATE VIEW DEMAND AS SELECT * FROM TEMP, RESULT
	CREATE VIEW ANSWER AS SELECT sum * eff_factor AS ANS FROM DEMAND
	CREATE VIEW SPRINGWEATHER AS SELECT AVG(avg_temp) FROM WEATHER WHERE MONTH >= 3 AND MONTH <= 6;
	RETURN QUERY
	SELECT * FROM answer, springweather
END

$fuc$ LANGUAGE plpgsql;

